### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by afterimagex** [letmaik/vscode-netron#1]
I don't know how to use it.

**Comment by renyi581176** [comment]
same question

**Comment by Flova** [comment]
Install it using the extensions tab in vs code. 
![image](https://user-images.githubusercontent.com/15075613/125161974-bf38c200-e185-11eb-9030-9ee8b7c89e68.png)

**Comment by letmaik** [comment]
@Flova I never published this extension to the marketplace due to all the caveats listed in the README and the unwillingness of the Netron author to do anything about them. This repo got forked at https://github.com/talshalti/netron and published from there to the VS Code marketplace (which is what you refer to).
